### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Khanggggggggggg** [SealedSaucer/Fake-Streamer#3]
c [RpcError]: Value "CLIENT_ID" is not snowflake.
    at u (/home/runner/Fake-Streamer/node_modules/discordrpcgenerator/index.js:1:1565)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.getRpcImage (/home/runner/Fake-Streamer/node_modules/discordrpcgenerator/index.js:1:8201)

**Comment by SealedSaucer** [comment]
Check the video linked on the repo once it's public again.
